### ISSUE TITLE
Please provide an option to toggle the price sync on/off

### ISSUE THREAD

**Issue by MrCaterpillarz** [mirakl/magento2-seller-connector#32]
We use the special price field for other stores, so would prefer to turn off price sync and just set our offer prices manually on mirakl.

We just want to sync the stock to mirakl, nothing else.

Should be standard feature to independently toggle orders/prices/stock from the sync, or to at least allow us to specify a custom field for the prices.

Magento 2 doesnt allow you to set prices on a storeview level, so it is no good unless we setup a whole independent website for each marketplace we want to sell on mirakl, and whilst this might be the solution, its alot of work to have to do just to ensure that the information is dedicated for that marketplace.

Perhaps there needs to be a warning stated at the beginning 'Please ensure you setup an independent website scope per marketplace in order to use this plugin effectively, but only because we dont allow you to specify your own custom fields for prices, nor allow you to turn off parts of the sync'.

**Comment by JPGrandclementMirakl** [comment]
Hello,

Thank you for reaching us!
I understand your desire for customization in managing prices on Mirakl Connector. Currently, our module does not allow for such configuration. However, you may consider developing this functionality yourself by overriding the connector feature.
If you have development skills or work with a technical team, it is possible to add custom features to your Mirakl instance to meet your specific needs. 

Please note that starting H2 2024, there will no longer be any support from our support teams for this connector, because we recently released the new Mirakl Magento Connect Connector that enables you to integrate your Magento store with all our marketplaces via our platform Mirakl Connect.

I will update the readme of this repository to better inform users, we are sorry for the inconvenience.

Regards,
JP

**Comment by MrCaterpillarz** [comment]
Thank you for your reply.

Sorry for moaning. I found a quick solution. I was able to change the filter in the listings manager to remove the items in the listing, and then cleared the listings from the overview pane before it had a chance to mirror the changes on mirakl (they all had 'to be deleted' as their status. So now I can keep the listings on Mirakl forever and update the prices/stocks manually from there. Another benefit is we won't keep getting email notifications every hour about any little change to the listings.

many thanks
